pub const PREFIX: &str = "/app/v3/api";

pub const ROUTES: &[(&str, &str, &str)] = &[
    ("GET", "/app/v3/api/prompts/nodes/tree", "nodes.tree.list"),
    ("GET", "/app/v3/api/prompts/boards/{boardId}/topics", "topics.list"),
    ("POST", "/app/v3/api/prompts/topics", "topics.create"),
    ("GET", "/app/v3/api/prompts/topics/{topicId}", "topics.retrieve"),
    ("PATCH", "/app/v3/api/prompts/topics/{topicId}", "topics.update"),
    ("DELETE", "/app/v3/api/prompts/topics/{topicId}", "topics.delete"),
    ("GET", "/app/v3/api/prompts/topics/{topicId}/replies", "topics.replies.list"),
    ("POST", "/app/v3/api/prompts/topics/{topicId}/replies", "topics.replies.create"),
    ("PATCH", "/app/v3/api/prompts/replies/{replyId}", "replies.update"),
    ("DELETE", "/app/v3/api/prompts/replies/{replyId}", "replies.delete"),
    ("GET", "/app/v3/api/prompts/topics/{topicId}/revisions", "topics.revisions.list"),
    ("GET", "/app/v3/api/prompts/replies/{replyId}/revisions", "replies.revisions.list"),
    ("PUT", "/app/v3/api/prompts/questions/{topicId}/accepted_reply", "questions.acceptedReply.update"),
    ("DELETE", "/app/v3/api/prompts/questions/{topicId}/accepted_reply", "questions.acceptedReply.delete"),
    ("POST", "/app/v3/api/prompts/polls/{pollId}/votes", "polls.votes.create"),
    ("POST", "/app/v3/api/prompts/reactions", "reactions.create"),
    ("POST", "/app/v3/api/prompts/votes", "votes.create"),
    ("POST", "/app/v3/api/prompts/bookmarks", "bookmarks.create"),
    ("PATCH", "/app/v3/api/prompts/read_state/topics/{topicId}", "readState.topics.update"),
    ("POST", "/app/v3/api/prompts/reports", "reports.create"),
    ("GET", "/app/v3/api/prompts/feed", "feed.list"),
    ("GET", "/app/v3/api/prompts/search", "search.query"),
];
