use crate::domain::commands::*;
use crate::domain::models::*;
use crate::domain::results::*;
use crate::error::PromptsServiceError;
use crate::value_objects::PromptsRequestContext;

pub trait PromptsRepository {
    fn list_node_tree(&self, ctx: &PromptsRequestContext, command: &ListNodeTreeCommand) -> Result<NodeTreeResult, PromptsServiceError>;
    fn list_nodes(&self, ctx: &PromptsRequestContext, command: &ListNodesCommand) -> Result<NodePageResult, PromptsServiceError>;
    fn list_topics(&self, ctx: &PromptsRequestContext, command: &ListTopicsCommand) -> Result<TopicPageResult, PromptsServiceError>;
    fn retrieve_topic_by_slug(&self, ctx: &PromptsRequestContext, command: &RetrieveTopicBySlugCommand) -> Result<PromptsTopic, PromptsServiceError>;
    fn create_topic(&self, ctx: &PromptsRequestContext, command: &CreateTopicCommand) -> Result<PromptsTopic, PromptsServiceError>;
    fn retrieve_topic(&self, ctx: &PromptsRequestContext, topic_id: i64) -> Result<PromptsTopic, PromptsServiceError>;
    fn update_topic(&self, ctx: &PromptsRequestContext, command: &UpdateTopicCommand) -> Result<PromptsTopic, PromptsServiceError>;
    fn delete_topic(&self, ctx: &PromptsRequestContext, command: &DeleteTopicCommand) -> Result<CommandResult, PromptsServiceError>;
    fn list_replies(&self, ctx: &PromptsRequestContext, command: &ListRepliesCommand) -> Result<ReplyPageResult, PromptsServiceError>;
    fn create_reply(&self, ctx: &PromptsRequestContext, command: &CreateReplyCommand) -> Result<PromptsReply, PromptsServiceError>;
    fn update_reply(&self, ctx: &PromptsRequestContext, command: &UpdateReplyCommand) -> Result<PromptsReply, PromptsServiceError>;
    fn delete_reply(&self, ctx: &PromptsRequestContext, command: &DeleteReplyCommand) -> Result<CommandResult, PromptsServiceError>;
    fn accept_reply(&self, ctx: &PromptsRequestContext, command: &AcceptReplyCommand) -> Result<PromptsTopic, PromptsServiceError>;
    fn clear_accepted_reply(&self, ctx: &PromptsRequestContext, command: &ClearAcceptedReplyCommand) -> Result<CommandResult, PromptsServiceError>;
    fn create_report(&self, ctx: &PromptsRequestContext, command: &CreateReportCommand) -> Result<CommandResult, PromptsServiceError>;
    fn list_feed(&self, ctx: &PromptsRequestContext, command: &ListFeedCommand) -> Result<FeedPageResult, PromptsServiceError>;
    fn query_search(&self, ctx: &PromptsRequestContext, command: &QuerySearchCommand) -> Result<SearchResult, PromptsServiceError>;
    fn list_moderation_queue(&self, ctx: &PromptsRequestContext, command: &ListModerationQueueCommand) -> Result<ModerationQueueResult, PromptsServiceError>;
    fn create_moderation_decision(&self, ctx: &PromptsRequestContext, command: &CreateModerationDecisionCommand) -> Result<ModerationDecisionResult, PromptsServiceError>;
    fn rebuild_search_projection(&self, ctx: &PromptsRequestContext, command: &RebuildSearchProjectionCommand) -> Result<CommandResult, PromptsServiceError>;
    fn rebuild_stats(&self, ctx: &PromptsRequestContext, command: &RebuildStatsCommand) -> Result<CommandResult, PromptsServiceError>;
    fn list_pending_outbox_events(
        &self,
        ctx: &PromptsRequestContext,
        command: &PublishOutboxCommand,
    ) -> Result<Vec<PromptsOutboxEvent>, PromptsServiceError>;
    fn mark_outbox_published(&self, ctx: &PromptsRequestContext, event_id: i64) -> Result<(), PromptsServiceError>;
    fn list_topic_revisions(&self, ctx: &PromptsRequestContext, command: &ListTopicRevisionsCommand) -> Result<TopicRevisionPageResult, PromptsServiceError>;
    fn list_reply_revisions(&self, ctx: &PromptsRequestContext, command: &ListReplyRevisionsCommand) -> Result<ReplyRevisionPageResult, PromptsServiceError>;
    fn create_poll_vote(&self, ctx: &PromptsRequestContext, command: &CreatePollVoteCommand) -> Result<CommandResult, PromptsServiceError>;
    fn create_reaction(&self, ctx: &PromptsRequestContext, command: &CreateReactionCommand) -> Result<CommandResult, PromptsServiceError>;
    fn create_vote(&self, ctx: &PromptsRequestContext, command: &CreateVoteCommand) -> Result<CommandResult, PromptsServiceError>;
    fn update_bookmark(&self, ctx: &PromptsRequestContext, command: &UpdateBookmarkCommand) -> Result<CommandResult, PromptsServiceError>;
    fn update_read_state(&self, ctx: &PromptsRequestContext, command: &UpdateReadStateCommand) -> Result<CommandResult, PromptsServiceError>;
    fn pin_topic(&self, ctx: &PromptsRequestContext, command: &PinTopicCommand) -> Result<CommandResult, PromptsServiceError>;
    fn feature_topic(&self, ctx: &PromptsRequestContext, command: &FeatureTopicCommand) -> Result<CommandResult, PromptsServiceError>;
    fn lock_topic(&self, ctx: &PromptsRequestContext, command: &LockTopicCommand) -> Result<CommandResult, PromptsServiceError>;
    fn unpin_topic(&self, ctx: &PromptsRequestContext, command: &PinTopicCommand) -> Result<CommandResult, PromptsServiceError>;
    fn unfeature_topic(&self, ctx: &PromptsRequestContext, command: &FeatureTopicCommand) -> Result<CommandResult, PromptsServiceError>;
    fn unlock_topic(&self, ctx: &PromptsRequestContext, command: &LockTopicCommand) -> Result<CommandResult, PromptsServiceError>;
    fn move_topic(&self, ctx: &PromptsRequestContext, command: &MoveTopicCommand) -> Result<CommandResult, PromptsServiceError>;
    fn create_node(&self, ctx: &PromptsRequestContext, command: &CreateNodeCommand) -> Result<PromptsNode, PromptsServiceError>;
    fn update_node(&self, ctx: &PromptsRequestContext, command: &UpdateNodeCommand) -> Result<PromptsNode, PromptsServiceError>;
    fn delete_node(&self, ctx: &PromptsRequestContext, command: &DeleteNodeCommand) -> Result<CommandResult, PromptsServiceError>;
    fn list_moderation_cases(&self, ctx: &PromptsRequestContext, command: &ListModerationCasesCommand) -> Result<ModerationCasePageResult, PromptsServiceError>;
    fn create_moderation_case(&self, ctx: &PromptsRequestContext, command: &CreateModerationCaseCommand) -> Result<PromptsModerationCase, PromptsServiceError>;
    fn retrieve_moderation_case(&self, ctx: &PromptsRequestContext, command: &RetrieveModerationCaseCommand) -> Result<PromptsModerationCase, PromptsServiceError>;
    fn list_sanctions(&self, ctx: &PromptsRequestContext, command: &ListSanctionsCommand) -> Result<SanctionPageResult, PromptsServiceError>;
    fn create_sanction(&self, ctx: &PromptsRequestContext, command: &CreateSanctionCommand) -> Result<PromptsSanction, PromptsServiceError>;
    fn update_sanction(&self, ctx: &PromptsRequestContext, command: &UpdateSanctionCommand) -> Result<PromptsSanction, PromptsServiceError>;
    fn list_reputation_rules(&self, ctx: &PromptsRequestContext, command: &ListReputationRulesCommand) -> Result<ReputationRulePageResult, PromptsServiceError>;
    fn create_reputation_rule(&self, ctx: &PromptsRequestContext, command: &CreateReputationRuleCommand) -> Result<PromptsReputationRule, PromptsServiceError>;
    fn list_reputation_ledger(&self, ctx: &PromptsRequestContext, command: &ListReputationLedgerCommand) -> Result<ReputationLedgerPageResult, PromptsServiceError>;
    fn list_trust_levels(&self, ctx: &PromptsRequestContext, command: &ListTrustLevelsCommand) -> Result<TrustLevelPageResult, PromptsServiceError>;
    fn create_trust_level(&self, ctx: &PromptsRequestContext, command: &CreateTrustLevelCommand) -> Result<PromptsTrustLevel, PromptsServiceError>;
    fn list_badges(&self, ctx: &PromptsRequestContext, command: &ListBadgesCommand) -> Result<BadgePageResult, PromptsServiceError>;
    fn create_badge(&self, ctx: &PromptsRequestContext, command: &CreateBadgeCommand) -> Result<PromptsBadge, PromptsServiceError>;
    fn list_board_stats(&self, ctx: &PromptsRequestContext, command: &ListBoardStatsCommand) -> Result<BoardStatsPageResult, PromptsServiceError>;
    fn list_topic_stats(&self, ctx: &PromptsRequestContext, command: &ListTopicStatsCommand) -> Result<TopicStatsPageResult, PromptsServiceError>;
    fn create_audit_action(&self, ctx: &PromptsRequestContext, command: &CreateAuditActionCommand) -> Result<PromptsAuditAction, PromptsServiceError>;
    fn list_audit_actions(&self, ctx: &PromptsRequestContext, command: &ListAuditActionsCommand) -> Result<AuditActionPageResult, PromptsServiceError>;
    fn list_tags(&self, ctx: &PromptsRequestContext, command: &ListTagsCommand) -> Result<TagPageResult, PromptsServiceError>;
    fn list_topic_prefixes(&self, ctx: &PromptsRequestContext, command: &ListTopicPrefixesCommand) -> Result<TopicPrefixPageResult, PromptsServiceError>;
    fn create_topic_prefix(&self, ctx: &PromptsRequestContext, command: &CreateTopicPrefixCommand) -> Result<PromptsTopicPrefix, PromptsServiceError>;
    fn create_space(&self, ctx: &PromptsRequestContext, command: &CreateSpaceCommand) -> Result<PromptsSpace, PromptsServiceError>;
    fn update_space(&self, ctx: &PromptsRequestContext, command: &UpdateSpaceCommand) -> Result<PromptsSpace, PromptsServiceError>;
    fn create_attachment(&self, ctx: &PromptsRequestContext, command: &CreateAttachmentCommand) -> Result<PromptsAttachment, PromptsServiceError>;
    fn create_subscription(&self, ctx: &PromptsRequestContext, command: &CreateSubscriptionCommand) -> Result<PromptsSubscription, PromptsServiceError>;
    fn update_subscription(&self, ctx: &PromptsRequestContext, command: &UpdateSubscriptionCommand) -> Result<PromptsSubscription, PromptsServiceError>;
    fn list_subscriptions(&self, ctx: &PromptsRequestContext, command: &ListSubscriptionsCommand) -> Result<SubscriptionPageResult, PromptsServiceError>;
    fn check_space_has_topics(&self, ctx: &PromptsRequestContext, space_id: i64) -> Result<bool, PromptsServiceError>;
    fn check_node_cycle(&self, ctx: &PromptsRequestContext, node_id: i64, new_parent_id: i64) -> Result<bool, PromptsServiceError>;
    fn check_node_is_board(&self, ctx: &PromptsRequestContext, node_id: i64) -> Result<bool, PromptsServiceError>;
    fn check_board_exists(&self, ctx: &PromptsRequestContext, board_id: i64) -> Result<bool, PromptsServiceError>;
    fn check_owner_exists(&self, ctx: &PromptsRequestContext, owner_type: &str, owner_id: i64) -> Result<bool, PromptsServiceError>;
    fn check_poll_exists(&self, ctx: &PromptsRequestContext, poll_id: i64) -> Result<bool, PromptsServiceError>;
    fn count_poll_votes(&self, ctx: &PromptsRequestContext, poll_id: i64) -> Result<i64, PromptsServiceError>;
    fn check_poll_selection_mode(&self, ctx: &PromptsRequestContext, poll_id: i64) -> Result<String, PromptsServiceError>;
    fn check_active_vote(&self, ctx: &PromptsRequestContext, target_type: &str, target_id: i64, actor_user_id: i64) -> Result<bool, PromptsServiceError>;
    fn check_active_sanctions(&self, ctx: &PromptsRequestContext, user_id: i64) -> Result<Vec<PromptsSanction>, PromptsServiceError>;
    fn check_active_appeal(&self, ctx: &PromptsRequestContext, sanction_id: Option<i64>, case_id: Option<i64>, appellant_user_id: i64) -> Result<bool, PromptsServiceError>;
    fn count_topics_in_space(&self, ctx: &PromptsRequestContext, space_id: i64) -> Result<i64, PromptsServiceError>;
    fn get_next_revision_no(&self, ctx: &PromptsRequestContext, topic_id: i64) -> Result<i32, PromptsServiceError>;
    fn get_next_reply_no(&self, ctx: &PromptsRequestContext, topic_id: i64) -> Result<i32, PromptsServiceError>;
    fn get_next_case_no(&self, ctx: &PromptsRequestContext, tenant_id: i64) -> Result<String, PromptsServiceError>;
    fn check_duplicate_queue_item(&self, ctx: &PromptsRequestContext, target_type: &str, target_id: i64, source_type: &str) -> Result<bool, PromptsServiceError>;
    fn check_idempotency_key(&self, ctx: &PromptsRequestContext, key: &str, operation_id: &str) -> Result<Option<PromptsIdempotencyRecord>, PromptsServiceError>;
    fn check_message_id_exists(&self, ctx: &PromptsRequestContext, source_system: &str, message_id: &str, consumer_name: &str) -> Result<bool, PromptsServiceError>;
    fn check_message_payload_hash(&self, ctx: &PromptsRequestContext, source_system: &str, message_id: &str, consumer_name: &str, payload_hash: &str) -> Result<bool, PromptsServiceError>;
    fn get_reputation_balance(&self, ctx: &PromptsRequestContext, user_id: i64) -> Result<i64, PromptsServiceError>;
    fn get_topic_stats(&self, ctx: &PromptsRequestContext, topic_id: i64) -> Result<PromptsTopicStats, PromptsServiceError>;
    fn get_board_stats(&self, ctx: &PromptsRequestContext, board_id: i64) -> Result<PromptsBoardStats, PromptsServiceError>;
    fn get_member_stats(&self, ctx: &PromptsRequestContext, user_id: i64) -> Result<PromptsMemberStats, PromptsServiceError>;
    fn update_tag_usage_count(&self, ctx: &PromptsRequestContext, tag_id: i64) -> Result<(), PromptsServiceError>;
    fn update_unread_count(&self, ctx: &PromptsRequestContext, topic_id: i64, user_id: i64) -> Result<(), PromptsServiceError>;
    fn get_notification_preferences(&self, ctx: &PromptsRequestContext, user_id: i64, event_type: &str) -> Result<Vec<PromptsNotificationPreference>, PromptsServiceError>;
    fn insert_outbox_event(&self, ctx: &PromptsRequestContext, event: &PromptsOutboxEvent) -> Result<(), PromptsServiceError>;
    fn update_topic_stats(&self, ctx: &PromptsRequestContext, topic_id: i64) -> Result<(), PromptsServiceError>;
    fn update_board_stats(&self, ctx: &PromptsRequestContext, board_id: i64) -> Result<(), PromptsServiceError>;
    fn update_member_stats(&self, ctx: &PromptsRequestContext, user_id: i64) -> Result<(), PromptsServiceError>;
}
