pub const PREFIX: &str = "/backend/v3/api";

pub const ROUTES: &[(&str, &str, &str)] = &[
    ("GET", "/backend/v3/api/prompts/nodes", "nodes.list"),
    ("POST", "/backend/v3/api/prompts/nodes", "nodes.create"),
    ("PATCH", "/backend/v3/api/prompts/nodes/{nodeId}", "nodes.update"),
    ("DELETE", "/backend/v3/api/prompts/nodes/{nodeId}", "nodes.delete"),
    ("GET", "/backend/v3/api/prompts/topic_prefixes", "topicPrefixes.list"),
    ("POST", "/backend/v3/api/prompts/topic_prefixes", "topicPrefixes.create"),
    ("GET", "/backend/v3/api/prompts/topics", "topics.list"),
    ("GET", "/backend/v3/api/prompts/topics/{topicId}", "topics.retrieve"),
    ("PATCH", "/backend/v3/api/prompts/topics/{topicId}", "topics.update"),
    ("DELETE", "/backend/v3/api/prompts/topics/{topicId}", "topics.delete"),
    ("POST", "/backend/v3/api/prompts/topics/{topicId}/pin", "topics.pin.create"),
    ("DELETE", "/backend/v3/api/prompts/topics/{topicId}/pin", "topics.pin.delete"),
    ("POST", "/backend/v3/api/prompts/topics/{topicId}/feature", "topics.feature.create"),
    ("DELETE", "/backend/v3/api/prompts/topics/{topicId}/feature", "topics.feature.delete"),
    ("POST", "/backend/v3/api/prompts/topics/{topicId}/lock", "topics.lock.create"),
    ("DELETE", "/backend/v3/api/prompts/topics/{topicId}/lock", "topics.lock.delete"),
    ("POST", "/backend/v3/api/prompts/topics/{topicId}/move", "topics.move.create"),
    ("GET", "/backend/v3/api/prompts/moderation/queue", "moderation.queue.list"),
    ("GET", "/backend/v3/api/prompts/moderation/cases", "moderation.cases.list"),
    ("POST", "/backend/v3/api/prompts/moderation/cases", "moderation.cases.create"),
    ("GET", "/backend/v3/api/prompts/moderation/cases/{caseId}", "moderation.cases.retrieve"),
    ("POST", "/backend/v3/api/prompts/moderation/cases/{caseId}/decisions", "moderation.cases.decisions.create"),
    ("GET", "/backend/v3/api/prompts/sanctions", "sanctions.list"),
    ("POST", "/backend/v3/api/prompts/sanctions", "sanctions.create"),
    ("PATCH", "/backend/v3/api/prompts/sanctions/{sanctionId}", "sanctions.update"),
    ("GET", "/backend/v3/api/prompts/reputation/rules", "reputation.rules.list"),
    ("POST", "/backend/v3/api/prompts/reputation/rules", "reputation.rules.create"),
    ("GET", "/backend/v3/api/prompts/reputation/ledger", "reputation.ledger.list"),
    ("GET", "/backend/v3/api/prompts/trust_levels", "trustLevels.list"),
    ("POST", "/backend/v3/api/prompts/trust_levels", "trustLevels.create"),
    ("GET", "/backend/v3/api/prompts/badges", "badges.list"),
    ("POST", "/backend/v3/api/prompts/badges", "badges.create"),
    ("GET", "/backend/v3/api/prompts/stats/boards", "stats.boards.list"),
    ("GET", "/backend/v3/api/prompts/stats/topics", "stats.topics.list"),
    ("POST", "/backend/v3/api/prompts/search/reindex", "search.reindex.create"),
    ("GET", "/backend/v3/api/prompts/audit/actions", "audit.actions.list"),
];
